-- Data

SELECT DISTINCT $A$.RIID_, $A$.BA_PID, $A$.BA_IMG_URL, $A$.BA_RACK_SPACE, $A$.BA_PNAME, $A$.BA_PPRICE, 1 as Entry_ID FROM $A$ WHERE TO_CHAR($A$.MODIFIED_DATE_, 'DD-MM-YYYY') = TO_CHAR(current_timestamp, 'DD-MM-YYYY') union SELECT DISTINCT $A$.RIID_, $A$.BA_PID, $A$.BA_IMG_URL, $A$.BA_RACK_SPACE, $A$.BA_PNAME, $A$.BA_PPRICE, 1 as Entry_ID FROM $A$ WHERE TO_CHAR($A$.MODIFIED_DATE_, 'DD-MM-YYYY') = TO_CHAR( current_timestamp - interval '11' hour, 'DD-MM-YYYY' )


-- MAX already in place ( to verify )
-- SELECT DISTINCT RIID_, regexp_substr(BA_PID, '[^,]+', 1, level) as BA_PRODUCTID, BA_IMG_URL, BA_RACK_SPACE,BA_PNAME,BA_PPRICE, 1 as ENTRY_ID FROM ( SELECT DISTINCT $A$.RIID_, $A$.BA_PID, $A$.BA_IMG_URL, $A$.BA_RACK_SPACE,BA_PNAME, BA_PPRICE FROM $A$ WHERE TO_CHAR($A$.MODIFIED_DATE_, 'DD-MM-YYYY') = TO_CHAR(current_timestamp, 'DD-MM-YYYY') ) TEMP CONNECT BY level <= regexp_count(BA_PID, ',') + 1

-- Inclusion List

SELECT $B$.RIID_, $B$.EMAIL_ADDRESS_ FROM ( SELECT $A$.RIID_ FROM $A$ WHERE TO_CHAR($A$.MODIFIED_DATE_, 'DD-MM-YYYY') = TO_CHAR(current_timestamp, 'DD-MM-YYYY') ) INCLUSION_LIST, $B$ WHERE INCLUSION_LIST.RIID_ = $B$.RIID_ union SELECT $B$.RIID_, $B$.EMAIL_ADDRESS_ FROM ( SELECT $A$.RIID_ FROM $A$ WHERE TO_CHAR($A$.MODIFIED_DATE_, 'DD-MM-YYYY') = TO_CHAR( current_timestamp - interval '11' hour, 'DD-MM-YYYY' ) ) INCLUSION_LIST, $B$ WHERE INCLUSION_LIST.RIID_ = $B$.RIID_

-- MAX already in place ( to verify )
-- SELECT $B$.RIID_,$B$.EMAIL_ADDRESS_ FROM ( SELECT $A$.RIID_ FROM $A$ WHERE TO_CHAR( $A$.MODIFIED_DATE_, 'DD-MM-YYYY') =TO_CHAR(current_timestamp ,'DD-MM-YYYY') )INCLUSION_LIST,$B$ WHERE INCLUSION_LIST.RIID_=$B$.RIID_

